env:
  global: []
install:
  - ( echo Setup OSX )
script:
  - ( (pwd; cd /) )
  - ( (pwd; cd /) )
  - ( (pwd; cd /) )
  - ( pwd; cd / )
  - ( pwd; cd / )
  - ( pwd; cd / )
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true
